# Generated by Django 5.1.7 on 2025-04-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_postlike_post_remove_postlike_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                choices=[
                    ("python", "Python"),
                    ("django", "Django"),
                    ("react", "React"),
                    ("kotlin", "Kotlin"),
                    ("flutter", "Flutter"),
                ],
                max_length=100,
            ),
        ),
    ]
